"""Study Mode — topic explanations (text content)."""

TOPICS = [
    "Set Theory",
    "Relations",
    "Propositional Logic",
    "Rules of Inference",
    "Proof Methods",
    "Mathematical Induction",
    "Sequences & Summations",
    "Combinatorics",
    "Graph Theory",
]

EXPLANATIONS: dict[str, dict] = {
    "Set Theory": {
        "summary": "A set is an unordered collection of distinct objects. Sets are the foundation of all mathematics and computer science.",
        "key_concepts": [
            ("Notation", "A = {1, 2, 3} — curly braces list elements; ∈ means 'belongs to', ∉ means 'does not belong to'."),
            ("Subset", "A ⊆ B means every element of A is also in B. A ⊂ B means proper subset (A ≠ B)."),
            ("Union", "A ∪ B = {x | x ∈ A or x ∈ B} — everything in either set."),
            ("Intersection", "A ∩ B = {x | x ∈ A and x ∈ B} — only what's in both."),
            ("Difference", "A − B = {x | x ∈ A and x ∉ B} — elements in A but not in B."),
            ("Complement", "Ā = U − A — everything in the universe NOT in A."),
            ("Cartesian Product", "A × B = {(a,b) | a∈A, b∈B} — all ordered pairs."),
            ("Power Set", "𝒫(A) = set of all subsets of A. If |A|=n then |𝒫(A)|=2ⁿ."),
        ],
        "formulas": [
            "|A ∪ B| = |A| + |B| − |A ∩ B|  (Inclusion-Exclusion)",
            "De Morgan: (A ∪ B)' = A' ∩ B'",
            "De Morgan: (A ∩ B)' = A' ∪ B'",
            "Distributive: A ∩ (B ∪ C) = (A ∩ B) ∪ (A ∩ C)",
        ],
        "tip": "Think of sets as circles in a Venn diagram. Union = everything in either circle. Intersection = the overlapping region.",
    },
    "Relations": {
        "summary": "A binary relation R from A to B is a subset of A × B. Relations model connections between objects.",
        "key_concepts": [
            ("Reflexive", "∀a∈A: (a,a)∈R — every element relates to itself (identity on diagonal in matrix)."),
            ("Symmetric", "∀a,b: (a,b)∈R → (b,a)∈R — if a→b then b→a."),
            ("Antisymmetric", "∀a,b: (a,b)∈R ∧ (b,a)∈R → a=b — no two-way streets except self-loops."),
            ("Transitive", "∀a,b,c: (a,b)∈R ∧ (b,c)∈R → (a,c)∈R — shortcuts exist."),
            ("Equivalence Relation", "Reflexive + Symmetric + Transitive. Partitions set into equivalence classes."),
            ("Partial Order", "Reflexive + Antisymmetric + Transitive. e.g., ≤ on integers."),
            ("Closure", "Smallest extension of R that satisfies a property (reflexive/symmetric/transitive)."),
        ],
        "formulas": [
            "Transitive closure: Warshall's algorithm — O(n³)",
            "Composition: (R∘S) = {(a,c) | ∃b: (a,b)∈R ∧ (b,c)∈S}",
            "Equivalence class [a] = {b∈A | (a,b)∈R}",
        ],
        "tip": "For the matrix of a relation: reflexive → 1s on main diagonal; symmetric → matrix equals its transpose; transitive → M² ≤ M (Boolean product).",
    },
    "Propositional Logic": {
        "summary": "Propositional logic studies how propositions (statements that are T or F) combine via logical connectives.",
        "key_concepts": [
            ("Negation ¬p", "True when p is False. NOT gate in circuits."),
            ("Conjunction p∧q", "True only when BOTH p and q are True. AND gate."),
            ("Disjunction p∨q", "True when AT LEAST ONE of p, q is True. OR gate."),
            ("Implication p→q", "False ONLY when p is True and q is False. 'If p then q'."),
            ("Biconditional p↔q", "True when p and q have the SAME truth value."),
            ("Tautology", "Always True for all truth assignments (e.g., p∨¬p)."),
            ("Contradiction", "Always False (e.g., p∧¬p)."),
            ("Logical Equivalence", "p≡q means p↔q is a tautology."),
        ],
        "formulas": [
            "p→q ≡ ¬p∨q  (implication as disjunction)",
            "p↔q ≡ (p→q)∧(q→p)",
            "¬(p∧q) ≡ ¬p∨¬q  (De Morgan)",
            "¬(p∨q) ≡ ¬p∧¬q  (De Morgan)",
        ],
        "tip": "Implication p→q is your trickiest connective: it's only FALSE when the hypothesis (p) is TRUE but the conclusion (q) is FALSE. A false hypothesis makes the implication vacuously true.",
    },
    "Rules of Inference": {
        "summary": "Rules of inference are valid argument forms used to derive conclusions from premises in logical proofs.",
        "key_concepts": [
            ("Modus Ponens", "p, p→q ⊢ q  (most fundamental rule)"),
            ("Modus Tollens", "¬q, p→q ⊢ ¬p  (contrapositive reasoning)"),
            ("Hypothetical Syllogism", "p→q, q→r ⊢ p→r  (chain rule)"),
            ("Disjunctive Syllogism", "p∨q, ¬p ⊢ q  (process of elimination)"),
            ("Addition", "p ⊢ p∨q  (weaken to disjunction)"),
            ("Simplification", "p∧q ⊢ p  (extract one conjunct)"),
            ("Conjunction", "p, q ⊢ p∧q  (combine two facts)"),
            ("Resolution", "p∨q, ¬p∨r ⊢ q∨r  (key in automated reasoning)"),
        ],
        "formulas": [
            "An argument P₁,P₂,...,Pₙ ⊢ C is valid iff (P₁∧P₂∧...∧Pₙ)→C is a tautology",
        ],
        "tip": "To validate an argument: build a truth table. If every row where ALL premises are true also has the conclusion true, the argument is VALID.",
    },
    "Proof Methods": {
        "summary": "A mathematical proof is a rigorous logical argument establishing the truth of a statement beyond doubt.",
        "key_concepts": [
            ("Direct Proof", "Assume p. Use axioms and theorems to derive q. Best for 'If p then q' statements."),
            ("Proof by Contradiction", "Assume ¬q (negation of conclusion). Derive a logical contradiction. Therefore q must hold."),
            ("Proof by Contrapositive", "To prove p→q, instead prove its equivalent ¬q→¬p."),
            ("Proof by Cases", "Divide the problem space into exhaustive cases. Prove the claim for each case."),
            ("Existence Proof", "Constructive: exhibit the object. Non-constructive: show non-existence of its absence."),
            ("Uniqueness Proof", "Show existence, then show any two objects satisfying the conditions are equal."),
        ],
        "formulas": [
            "p→q ≡ ¬q→¬p  (contrapositive — logically equivalent)",
            "Proof by contradiction: assume (p∧¬q), derive ⊥ (contradiction)",
        ],
        "tip": "When stuck on a direct proof, try the contrapositive or contradiction. Contradiction is powerful when you need to prove something 'cannot happen'.",
    },
    "Mathematical Induction": {
        "summary": "Mathematical induction proves statements P(n) hold for all natural numbers n ≥ n₀ using two steps.",
        "key_concepts": [
            ("Base Case", "Prove P(n₀) is true for the starting value (usually n=1 or n=0)."),
            ("Inductive Hypothesis", "Assume P(k) is true for some arbitrary k ≥ n₀."),
            ("Inductive Step", "Using the assumption P(k), prove P(k+1) is also true."),
            ("Conclusion", "By the principle of induction, P(n) holds for all n ≥ n₀."),
            ("Strong Induction", "Assume P(j) for all j ≤ k, then prove P(k+1). Stronger hypothesis, same conclusion."),
        ],
        "formulas": [
            "Base: P(1) ✓ | Step: P(k)→P(k+1) ✓ | Conclusion: ∀n≥1 P(n) ✓",
            "Σᵢ₌₁ⁿ i = n(n+1)/2",
            "Σᵢ₌₁ⁿ i² = n(n+1)(2n+1)/6",
        ],
        "tip": "In the inductive step, you MUST use the inductive hypothesis somewhere. If you don't, you're doing something wrong. Look for where to substitute P(k).",
    },
    "Sequences & Summations": {
        "summary": "A sequence is an ordered list of numbers following a rule. Summation notation (Σ) compresses repeated addition.",
        "key_concepts": [
            ("Arithmetic Sequence", "aₙ = a₁ + (n-1)d. Constant difference d between terms."),
            ("Geometric Sequence", "aₙ = a₁·rⁿ⁻¹. Constant ratio r between terms."),
            ("Fibonacci Sequence", "F(n) = F(n-1) + F(n-2), F(1)=F(2)=1. Each term is sum of two before."),
            ("Summation Σ", "Σᵢ₌ₘⁿ f(i) = f(m) + f(m+1) + ... + f(n). Index runs from m to n."),
            ("Closed Form", "Express Σ without the sum sign. e.g., Σᵢ₌₁ⁿ i = n(n+1)/2."),
        ],
        "formulas": [
            "Arithmetic sum: Sₙ = n/2 · (a₁ + aₙ) = n/2 · (2a₁ + (n-1)d)",
            "Geometric sum: Sₙ = a₁(rⁿ-1)/(r-1) for r≠1",
            "Σᵢ₌₁ⁿ i² = n(n+1)(2n+1)/6",
            "Infinite geometric: S = a/(1-r) for |r|<1",
        ],
        "tip": "Always check the index bounds carefully in Σ notation. Σᵢ₌₀ⁿ vs Σᵢ₌₁ⁿ gives different results — off by the i=0 term.",
    },
    "Combinatorics": {
        "summary": "Combinatorics counts structured arrangements and selections. It answers: 'How many ways can this happen?'",
        "key_concepts": [
            ("Product Rule", "If task A has m ways and task B has n ways, both together: m × n ways."),
            ("Sum Rule", "If task A has m ways OR task B has n ways (exclusive): m + n ways."),
            ("Permutation P(n,r)", "Ordered selection of r from n: P(n,r) = n!/(n-r)!"),
            ("Combination C(n,r)", "Unordered selection of r from n: C(n,r) = n!/(r!(n-r)!)"),
            ("Pigeonhole Principle", "n+1 objects → n boxes ⟹ some box has ≥2 objects."),
            ("Inclusion-Exclusion", "|A∪B| = |A| + |B| - |A∩B|. Extends to more sets."),
        ],
        "formulas": [
            "P(n,r) = n!/(n-r)!  — order matters",
            "C(n,r) = n!/(r!(n-r)!)  — order doesn't matter",
            "C(n,r) = C(n,n-r)  (symmetry)",
            "Σₖ₌₀ⁿ C(n,k) = 2ⁿ  (sum of row n of Pascal's triangle)",
            "Generalized pigeonhole: ⌈N/k⌉ guaranteed in some box",
        ],
        "tip": "Key question: Does ORDER matter? If yes → Permutation. If no → Combination. P(n,r) = r! × C(n,r).",
    },
    "Graph Theory": {
        "summary": "A graph G=(V,E) consists of vertices (nodes) and edges (connections). Graphs model networks, maps, and relationships.",
        "key_concepts": [
            ("Simple Graph", "Undirected, no self-loops, no multiple edges between same pair."),
            ("Degree", "deg(v) = number of edges incident to v. Σdeg(v) = 2|E| (Handshaking Lemma)."),
            ("Path & Cycle", "Path: sequence of distinct vertices connected by edges. Cycle: path that returns to start."),
            ("Connected Graph", "There exists a path between every pair of vertices."),
            ("Euler Circuit", "Traverses every edge exactly once, returns to start. Exists iff all vertices have even degree."),
            ("Hamiltonian Circuit", "Visits every vertex exactly once. No simple characterization (NP-complete)."),
            ("Bipartite Graph", "Vertices split into V₁, V₂; edges only between sets. Iff no odd cycles."),
            ("Isomorphism", "Bijection f:V₁→V₂ preserving adjacency. Necessary: same |V|,|E|, degree sequence."),
        ],
        "formulas": [
            "Handshaking: Σdeg(v) = 2|E|",
            "Simple graph max edges: n(n-1)/2",
            "Tree: connected, |E| = |V| - 1, no cycles",
            "Euler path exists: exactly 0 or 2 vertices with odd degree",
        ],
        "tip": "For Euler circuits remember: EVEN degrees everywhere. For Euler paths: exactly TWO odd-degree vertices (they are the start and end).",
    },
}
