"""Study Mode — practice problem sets with step-by-step solutions."""

PROBLEM_SETS: dict[str, list[dict]] = {
    "Set Theory": [
        {
            "title": "Set Operations",
            "problem": "Given A = {1,2,3,4,5}, B = {3,4,5,6,7}, U = {1,2,...,8}. Find: A∪B, A∩B, A−B, B−A, Ā.",
            "steps": [
                "A∪B = {x | x∈A or x∈B} = {1,2,3,4,5,6,7}",
                "A∩B = {x | x∈A and x∈B} = {3,4,5}",
                "A−B = {x | x∈A and x∉B} = {1,2}",
                "B−A = {x | x∈B and x∉A} = {6,7}",
                "Ā = U−A = {6,7,8}",
            ],
            "answer": "A∪B={1,2,3,4,5,6,7}, A∩B={3,4,5}, A−B={1,2}, B−A={6,7}, Ā={6,7,8}",
        },
        {
            "title": "Power Set",
            "problem": "Find the power set of A = {a, b, c} and determine |𝒫(A)|.",
            "steps": [
                "The power set contains ALL subsets of A.",
                "Subsets with 0 elements: { ∅ }",
                "Subsets with 1 element: {a}, {b}, {c}",
                "Subsets with 2 elements: {a,b}, {a,c}, {b,c}",
                "Subsets with 3 elements: {a,b,c}",
                "Total: 1+3+3+1 = 8 = 2³",
            ],
            "answer": "𝒫(A) = {∅,{a},{b},{c},{a,b},{a,c},{b,c},{a,b,c}}, |𝒫(A)| = 8",
        },
        {
            "title": "Inclusion-Exclusion",
            "problem": "In a class of 50 students, 30 study CS, 20 study Math, and 10 study both. How many study CS or Math?",
            "steps": [
                "|CS| = 30, |Math| = 20, |CS∩Math| = 10",
                "Apply Inclusion-Exclusion: |CS∪Math| = |CS| + |Math| − |CS∩Math|",
                "|CS∪Math| = 30 + 20 − 10 = 40",
            ],
            "answer": "40 students study CS or Math (or both).",
        },
        {
            "title": "Cartesian Product",
            "problem": "A = {1,2}, B = {x,y,z}. Find A×B and |A×B|.",
            "steps": [
                "A×B = {(a,b) | a∈A, b∈B}",
                "List all pairs: (1,x),(1,y),(1,z),(2,x),(2,y),(2,z)",
                "|A×B| = |A|×|B| = 2×3 = 6",
            ],
            "answer": "A×B = {(1,x),(1,y),(1,z),(2,x),(2,y),(2,z)}, |A×B| = 6",
        },
        {
            "title": "Set Identity Proof",
            "problem": "Prove: A ∩ (B ∪ C) = (A ∩ B) ∪ (A ∩ C)  (Distributive Law).",
            "steps": [
                "Let x ∈ A ∩ (B ∪ C). Then x∈A and (x∈B or x∈C).",
                "Case 1: x∈A and x∈B → x∈(A∩B) → x∈(A∩B)∪(A∩C).",
                "Case 2: x∈A and x∈C → x∈(A∩C) → x∈(A∩B)∪(A∩C).",
                "So LHS ⊆ RHS.",
                "Now let x ∈ (A∩B)∪(A∩C). Then x∈A∩B or x∈A∩C.",
                "Either way x∈A and (x∈B or x∈C) → x∈A∩(B∪C).",
                "So RHS ⊆ LHS. Therefore LHS = RHS.  □",
            ],
            "answer": "Proven by showing mutual subset inclusion (both ⊆ directions).",
        },
    ],
    "Relations": [
        {
            "title": "Checking Properties",
            "problem": "R = {(1,1),(2,2),(3,3),(1,2),(2,1)} on A = {1,2,3}. Is R reflexive, symmetric, transitive?",
            "steps": [
                "Reflexive: Check (1,1),(2,2),(3,3) ∈ R. All present ✓",
                "Symmetric: Check all (a,b)∈R → (b,a)∈R.",
                "  (1,2)∈R → (2,1)∈R ✓, (2,1)∈R → (1,2)∈R ✓",
                "Transitive: Check all (a,b),(b,c)∈R → (a,c)∈R.",
                "  (1,2),(2,1) → need (1,1) ∈ R ✓",
                "  (2,1),(1,2) → need (2,2) ∈ R ✓",
                "  All cases check out ✓",
                "Since reflexive+symmetric+transitive: R is an equivalence relation.",
            ],
            "answer": "R is Reflexive ✓, Symmetric ✓, Transitive ✓ → Equivalence relation.",
        },
        {
            "title": "Equivalence Classes",
            "problem": "For the relation above, find the equivalence classes.",
            "steps": [
                "[1] = {x ∈ A | (1,x) ∈ R} = {1, 2} (since (1,1) and (1,2) ∈ R)",
                "[2] = {x ∈ A | (2,x) ∈ R} = {1, 2} (same class as [1])",
                "[3] = {x ∈ A | (3,x) ∈ R} = {3}",
                "The partition is: {{1,2}, {3}}",
            ],
            "answer": "Equivalence classes: {1,2} and {3}. Partition: {{1,2},{3}}.",
        },
        {
            "title": "Transitive Closure",
            "problem": "Find the transitive closure of R = {(1,2),(2,3),(3,1)} on {1,2,3}.",
            "steps": [
                "Start with R⁺ = R.",
                "Find compositions: (1,2)+(2,3) → add (1,3). (2,3)+(3,1) → add (2,1). (3,1)+(1,2) → add (3,2).",
                "New pairs: {(1,3),(2,1),(3,2)}",
                "Continue: (1,3)+(3,1) → add (1,1). (2,1)+(1,2) → add (2,2). (3,2)+(2,3) → add (3,3).",
                "More: (1,3)+(3,2) → (1,2) already in. (2,1)+(1,3) → add (2,3) already in.",
                "Transitive closure = {(1,1),(2,2),(3,3),(1,2),(1,3),(2,1),(2,3),(3,1),(3,2)} = A×A",
            ],
            "answer": "The transitive closure is A×A (complete relation) — this relation is cyclic.",
        },
        {
            "title": "Relation Composition",
            "problem": "R = {(1,2),(2,3)}, S = {(2,4),(3,4)}. Find S∘R.",
            "steps": [
                "S∘R = {(a,c) | ∃b: (a,b)∈R and (b,c)∈S}",
                "Check (1,2)∈R: is (2,?)∈S? (2,4)∈S → add (1,4).",
                "Check (2,3)∈R: is (3,?)∈S? (3,4)∈S → add (2,4).",
                "S∘R = {(1,4),(2,4)}",
            ],
            "answer": "S∘R = {(1,4),(2,4)}",
        },
        {
            "title": "Partial Order",
            "problem": "Is the 'divides' relation (a|b) on {1,2,3,6} a partial order?",
            "steps": [
                "Pairs: 1|1, 1|2, 1|3, 1|6, 2|2, 2|6, 3|3, 3|6, 6|6.",
                "Reflexive: a|a for all a ✓ (1|1, 2|2, 3|3, 6|6)",
                "Antisymmetric: a|b and b|a → a=b. This holds for positive integers ✓",
                "Transitive: a|b and b|c → a|c. e.g. 1|2, 2|6 → 1|6 ✓",
                "All three hold → partial order (POSET).",
            ],
            "answer": "Yes, divisibility is a partial order on {1,2,3,6}.",
        },
    ],
    "Propositional Logic": [
        {
            "title": "Truth Table",
            "problem": "Construct the truth table for (p → q) ↔ (¬p ∨ q).",
            "steps": [
                "List all 4 combinations of p,q truth values.",
                "p=T,q=T: p→q=T, ¬p∨q=F∨T=T. T↔T = T",
                "p=T,q=F: p→q=F, ¬p∨q=F∨F=F. F↔F = T",
                "p=F,q=T: p→q=T, ¬p∨q=T∨T=T. T↔T = T",
                "p=F,q=F: p→q=T, ¬p∨q=T∨F=T. T↔T = T",
                "All rows give T → this is a TAUTOLOGY.",
            ],
            "answer": "Tautology ✓ — p→q and ¬p∨q are logically equivalent.",
        },
        {
            "title": "Logical Equivalence",
            "problem": "Simplify ¬(p → q) using known equivalences.",
            "steps": [
                "p → q ≡ ¬p ∨ q  (implication equivalence)",
                "¬(p → q) ≡ ¬(¬p ∨ q)  (apply negation)",
                "¬(¬p ∨ q) ≡ ¬(¬p) ∧ ¬q  (De Morgan's law)",
                "¬(¬p) ∧ ¬q ≡ p ∧ ¬q  (double negation)",
            ],
            "answer": "¬(p → q) ≡ p ∧ ¬q",
        },
        {
            "title": "Check Tautology",
            "problem": "Is (p ∨ ¬p) ∧ (q ∨ ¬q) a tautology?",
            "steps": [
                "p ∨ ¬p is always TRUE (Law of Excluded Middle).",
                "q ∨ ¬q is always TRUE (Law of Excluded Middle).",
                "T ∧ T = T for all values of p,q.",
            ],
            "answer": "Yes, this is a tautology.",
        },
        {
            "title": "Apply De Morgan",
            "problem": "Negate: 'It is raining AND it is cold' → formal notation and negation.",
            "steps": [
                "Let p = 'it is raining', q = 'it is cold'.",
                "Statement: p ∧ q",
                "Negation: ¬(p ∧ q)",
                "Apply De Morgan: ¬(p ∧ q) ≡ ¬p ∨ ¬q",
                "In English: 'It is NOT raining OR it is NOT cold.'",
            ],
            "answer": "¬(p ∧ q) ≡ ¬p ∨ ¬q — 'It is not raining or it is not cold.'",
        },
        {
            "title": "Implication Chain",
            "problem": "Given: p→q, q→r, p. Prove r.",
            "steps": [
                "Step 1: p is given (premise).",
                "Step 2: p→q is given. Apply Modus Ponens with p → conclude q.",
                "Step 3: q→r is given. Apply Modus Ponens with q → conclude r.",
            ],
            "answer": "r is proven. Used Modus Ponens twice.",
        },
    ],
    "Rules of Inference": [
        {
            "title": "Identify the Rule",
            "problem": "Premises: 'If you study, you pass.' 'You study.' Conclusion: 'You pass.' Name the rule and validate.",
            "steps": [
                "Let p = 'you study', q = 'you pass'.",
                "Premises: p→q (if you study, you pass), p (you study).",
                "Conclusion: q (you pass).",
                "Form: p→q, p ∴ q → This is MODUS PONENS.",
                "Valid ✓",
            ],
            "answer": "Modus Ponens. The argument is valid.",
        },
        {
            "title": "Modus Tollens Application",
            "problem": "Premises: 'If it is Sunday, shops are closed.' 'Shops are open.' What can we conclude?",
            "steps": [
                "Let p = 'it is Sunday', q = 'shops are closed'.",
                "Premises: p→q, ¬q (shops are open = shops are NOT closed).",
                "Apply Modus Tollens: p→q, ¬q ∴ ¬p",
                "Conclusion: ¬p = 'It is NOT Sunday.'",
            ],
            "answer": "It is not Sunday. (Modus Tollens)",
        },
        {
            "title": "Spot the Fallacy",
            "problem": "Premises: 'If it rains, the ground is wet.' 'The ground is wet.' Conclusion: 'It rained.' Valid?",
            "steps": [
                "Let p = 'it rained', q = 'ground is wet'.",
                "Premises: p→q, q. Conclusion: p.",
                "This is 'Affirming the Consequent' — a FALLACY.",
                "Counterexample: ground can be wet from sprinklers (q is true, p is false).",
                "The argument is INVALID.",
            ],
            "answer": "INVALID — Fallacy of affirming the consequent.",
        },
        {
            "title": "Build a Proof",
            "problem": "Given: p→q, q→r, ¬r. Prove: ¬p.",
            "steps": [
                "1. p→q  (premise)",
                "2. q→r  (premise)",
                "3. ¬r   (premise)",
                "4. p→r  (Hypothetical Syllogism on 1,2)",
                "5. ¬p   (Modus Tollens on 4,3: p→r and ¬r → ¬p)",
            ],
            "answer": "¬p proven using Hypothetical Syllogism + Modus Tollens.",
        },
        {
            "title": "Resolution Proof",
            "problem": "Given: p∨q and ¬p∨r. What can we conclude by Resolution?",
            "steps": [
                "Resolution rule: (p∨q) ∧ (¬p∨r) ⊢ q∨r.",
                "The p and ¬p cancel out (they are 'resolved').",
                "Conclusion: q ∨ r.",
            ],
            "answer": "q ∨ r (by Resolution).",
        },
    ],
    "Proof Methods": [
        {
            "title": "Direct Proof",
            "problem": "Prove: If n is odd, then n² is odd.",
            "steps": [
                "Assume n is odd.",
                "By definition: n = 2k + 1 for some integer k.",
                "n² = (2k+1)² = 4k² + 4k + 1 = 2(2k²+2k) + 1",
                "Let m = 2k²+2k (an integer). Then n² = 2m + 1.",
                "By definition of odd: n² is odd.  □",
            ],
            "answer": "n odd → n² = (2k+1)² = 2(2k²+2k)+1 is odd. □",
        },
        {
            "title": "Proof by Contradiction",
            "problem": "Prove: There is no largest even integer.",
            "steps": [
                "Assume for contradiction that there IS a largest even integer, call it N.",
                "Consider N + 2. Since N is even, N = 2k for some integer k.",
                "N + 2 = 2k + 2 = 2(k+1), which is also even.",
                "N + 2 > N, so N is NOT the largest even integer.",
                "CONTRADICTION. Our assumption was false.",
                "∴ There is no largest even integer.  □",
            ],
            "answer": "Contradiction reached: any 'largest' even integer N can be exceeded by N+2. □",
        },
        {
            "title": "Proof by Contrapositive",
            "problem": "Prove: If n² is even, then n is even.",
            "steps": [
                "Contrapositive: If n is odd, then n² is odd.",
                "Assume n is odd → n = 2k+1.",
                "n² = (2k+1)² = 4k²+4k+1 = 2(2k²+2k)+1 → odd.",
                "The contrapositive is proven. Therefore the original statement holds.  □",
            ],
            "answer": "Proved by contrapositive: n odd → n² odd, so n² even → n even. □",
        },
        {
            "title": "Proof by Cases",
            "problem": "Prove: n² + n is always even, for any integer n.",
            "steps": [
                "Case 1: n is even. n = 2k → n²+n = 4k²+2k = 2(2k²+k). Even ✓",
                "Case 2: n is odd. n = 2k+1 → n²+n = (2k+1)²+(2k+1) = 4k²+4k+1+2k+1 = 4k²+6k+2 = 2(2k²+3k+1). Even ✓",
                "Both cases give even. Since every integer is even or odd, this covers all cases.  □",
            ],
            "answer": "In both cases (n even, n odd), n²+n is even. □",
        },
        {
            "title": "Existence Proof",
            "problem": "Prove: There exists an integer n such that n² + n + 41 is not prime.",
            "steps": [
                "A constructive proof needs one counterexample.",
                "Try n = 41: 41² + 41 + 41 = 41(41+1+1) = 41 × 43.",
                "41 × 43 is clearly composite (not prime).",
                "∴ n = 41 is a witness.  □",
            ],
            "answer": "n = 41: n²+n+41 = 41×43 (composite). Existence proven constructively. □",
        },
    ],
    "Mathematical Induction": [
        {
            "title": "Sum Formula",
            "problem": "Prove by induction: 1 + 2 + 3 + ... + n = n(n+1)/2.",
            "steps": [
                "Base case (n=1): LHS = 1. RHS = 1·2/2 = 1. ✓",
                "Inductive hypothesis: Assume 1+2+...+k = k(k+1)/2.",
                "Inductive step: Show 1+2+...+k+(k+1) = (k+1)(k+2)/2.",
                "LHS = k(k+1)/2 + (k+1)  [by IH]",
                "    = (k+1)[k/2 + 1]",
                "    = (k+1)(k+2)/2  ✓",
                "By the principle of induction, the formula holds for all n≥1. □",
            ],
            "answer": "Proven: Σᵢ₌₁ⁿ i = n(n+1)/2. □",
        },
        {
            "title": "Inequality Proof",
            "problem": "Prove by induction: 2ⁿ ≥ n+1 for all n ≥ 1.",
            "steps": [
                "Base case (n=1): 2¹ = 2 ≥ 1+1 = 2. ✓",
                "Inductive hypothesis: Assume 2ᵏ ≥ k+1.",
                "Inductive step: Show 2^(k+1) ≥ k+2.",
                "2^(k+1) = 2·2ᵏ ≥ 2(k+1)  [by IH]",
                "2(k+1) = 2k+2 ≥ k+2 for k≥0 (since k≥0 → k ≥ 0) ✓",
                "So 2^(k+1) ≥ k+2. □",
            ],
            "answer": "2ⁿ ≥ n+1 for all n≥1. □",
        },
        {
            "title": "Divisibility",
            "problem": "Prove by induction: 3 | (n³ − n) for all n ≥ 1.",
            "steps": [
                "Base case (n=1): 1³−1 = 0. 3|0 ✓",
                "Inductive hypothesis: Assume 3|(k³−k).",
                "Inductive step: Show 3|((k+1)³−(k+1)).",
                "(k+1)³−(k+1) = k³+3k²+3k+1−k−1 = (k³−k) + 3k²+3k",
                "               = (k³−k) + 3k(k+1)",
                "3|(k³−k) by IH, and 3|3k(k+1) obviously.",
                "Sum of two multiples of 3 is divisible by 3. □",
            ],
            "answer": "3|(n³−n) for all n≥1. □",
        },
        {
            "title": "Strong Induction",
            "problem": "Prove: Every integer n ≥ 2 can be written as a product of primes.",
            "steps": [
                "Base case (n=2): 2 is prime, so it's a product of one prime. ✓",
                "Inductive hypothesis (strong): Assume every integer j with 2≤j<k can be written as product of primes.",
                "Inductive step for k:",
                "  Case 1: k is prime. Then k itself is a product of one prime. ✓",
                "  Case 2: k is composite. k = a·b where 2≤a,b<k.",
                "  By strong IH, a and b are products of primes.",
                "  So k = a·b is also a product of primes. ✓",
                "By strong induction, every n≥2 is a product of primes. □",
            ],
            "answer": "Fundamental Theorem of Arithmetic (existence part) proven by strong induction. □",
        },
    ],
    "Sequences & Summations": [
        {
            "title": "Arithmetic Sequence",
            "problem": "An arithmetic sequence has a₁=5 and d=3. Find a₁₀ and S₁₀.",
            "steps": [
                "General term: aₙ = a₁ + (n-1)d = 5 + (n-1)·3",
                "a₁₀ = 5 + 9·3 = 5 + 27 = 32",
                "Sum formula: Sₙ = n/2·(a₁+aₙ) = 10/2·(5+32) = 5·37 = 185",
            ],
            "answer": "a₁₀ = 32, S₁₀ = 185",
        },
        {
            "title": "Geometric Sequence",
            "problem": "A geometric sequence has a₁=3 and r=2. Find a₆ and S₆.",
            "steps": [
                "General term: aₙ = a₁·r^(n-1) = 3·2^(n-1)",
                "a₆ = 3·2⁵ = 3·32 = 96",
                "Sum: Sₙ = a₁(rⁿ-1)/(r-1) = 3(2⁶-1)/(2-1) = 3·63 = 189",
            ],
            "answer": "a₆ = 96, S₆ = 189",
        },
        {
            "title": "Closed Form Summation",
            "problem": "Evaluate Σᵢ₌₁¹⁰ (2i + 1).",
            "steps": [
                "Split: Σ(2i+1) = 2·Σi + Σ1",
                "Σᵢ₌₁¹⁰ i = 10·11/2 = 55",
                "Σᵢ₌₁¹⁰ 1 = 10",
                "Total = 2·55 + 10 = 110 + 10 = 120",
            ],
            "answer": "Σᵢ₌₁¹⁰ (2i+1) = 120  [equivalently: the 10 odd numbers 3,5,...,21 sum to 120]",
        },
        {
            "title": "Telescoping Sum",
            "problem": "Evaluate Σᵢ₌₁ⁿ [1/i − 1/(i+1)].",
            "steps": [
                "Write out partial sums (telescoping):",
                "(1/1 − 1/2) + (1/2 − 1/3) + ... + (1/n − 1/(n+1))",
                "Most terms cancel in pairs.",
                "Remaining: first term 1/1 and last term −1/(n+1)",
                "Sum = 1 − 1/(n+1) = n/(n+1)",
            ],
            "answer": "Σᵢ₌₁ⁿ [1/i − 1/(i+1)] = n/(n+1)",
        },
    ],
    "Combinatorics": [
        {
            "title": "Permutation vs Combination",
            "problem": "A class of 12 students. (a) How many ways to choose a president and secretary? (b) How many 3-person committees?",
            "steps": [
                "(a) Order matters (two distinct roles): P(12,2) = 12×11 = 132",
                "(b) Order doesn't matter (committee): C(12,3) = 12!/(3!9!) = 12×11×10/6 = 220",
            ],
            "answer": "(a) 132 ordered pairs; (b) 220 committees.",
        },
        {
            "title": "Pigeonhole Application",
            "problem": "Show that among any 5 integers, at least two have the same remainder when divided by 4.",
            "steps": [
                "Possible remainders mod 4: {0, 1, 2, 3} — 4 pigeonholes.",
                "We have 5 integers (pigeons).",
                "By Pigeonhole Principle: at least ⌈5/4⌉ = 2 integers share the same remainder.",
            ],
            "answer": "By Pigeonhole: 5 integers into 4 remainder classes → at least 2 share a remainder.",
        },
        {
            "title": "Inclusion-Exclusion (3 sets)",
            "problem": "80 students: 45 play cricket, 30 play football, 20 play tennis, 15 cricket+football, 10 cricket+tennis, 8 football+tennis, 5 all three. How many play at least one sport?",
            "steps": [
                "|C∪F∪T| = |C|+|F|+|T| − |C∩F| − |C∩T| − |F∩T| + |C∩F∩T|",
                "= 45+30+20 − 15−10−8 + 5",
                "= 95 − 33 + 5 = 67",
            ],
            "answer": "67 students play at least one sport.",
        },
        {
            "title": "Bit Strings",
            "problem": "How many bit strings of length 8 start with 1 or end with 00?",
            "steps": [
                "A = strings starting with 1: fix first bit, remaining 7 free → 2⁷ = 128",
                "B = strings ending with 00: fix last 2 bits, remaining 6 free → 2⁶ = 64",
                "A∩B = start 1 AND end 00: fix 3 bits, remaining 5 free → 2⁵ = 32",
                "|A∪B| = 128 + 64 − 32 = 160",
            ],
            "answer": "160 bit strings of length 8 start with 1 or end with 00.",
        },
        {
            "title": "Binomial Coefficient",
            "problem": "Expand (x+y)³ using the Binomial Theorem.",
            "steps": [
                "(x+y)³ = Σₖ₌₀³ C(3,k) x^(3-k) y^k",
                "k=0: C(3,0)x³y⁰ = x³",
                "k=1: C(3,1)x²y¹ = 3x²y",
                "k=2: C(3,2)x¹y² = 3xy²",
                "k=3: C(3,3)x⁰y³ = y³",
            ],
            "answer": "(x+y)³ = x³ + 3x²y + 3xy² + y³",
        },
    ],
    "Graph Theory": [
        {
            "title": "Graph Analysis",
            "problem": "G has vertices {A,B,C,D,E} and edges {AB,BC,CD,DE,AE,AC}. Find degrees, check if Eulerian.",
            "steps": [
                "List edges incident to each vertex:",
                "  A: AB, AE, AC → deg(A) = 3",
                "  B: AB, BC → deg(B) = 2",
                "  C: BC, CD, AC → deg(C) = 3",
                "  D: CD, DE → deg(D) = 2",
                "  E: DE, AE → deg(E) = 2",
                "Sum of degrees = 3+2+3+2+2 = 12 = 2×6 edges ✓",
                "Euler circuit needs ALL even degrees. A and C have odd degree (3).",
                "Euler circuit: NO. Euler path: exactly 2 odd-degree vertices → YES (A to C or C to A).",
            ],
            "answer": "Degrees: A=3,B=2,C=3,D=2,E=2. No Euler circuit; Euler path exists (A↔C).",
        },
        {
            "title": "Bipartite Check",
            "problem": "Is the graph with edges {(1,2),(1,4),(2,3),(3,4)} bipartite? If so, find the partition.",
            "steps": [
                "Try 2-coloring: color vertex 1 = Red.",
                "1's neighbors (2,4) = Blue.",
                "2's neighbors besides 1: vertex 3 = Red.",
                "3's neighbors besides 2: vertex 4. 4 is already Blue. Color of 3 = Red, neighbor of 4 = Red: ok (3-4 edge: Red-Blue ✓)",
                "Partition: V₁ = {1,3} (Red), V₂ = {2,4} (Blue).",
                "All edges go between V₁ and V₂ → bipartite ✓",
            ],
            "answer": "Bipartite. V₁={1,3}, V₂={2,4}.",
        },
        {
            "title": "Tree Properties",
            "problem": "A tree has 9 vertices. How many edges? What is the sum of all degrees?",
            "steps": [
                "A tree with n vertices has exactly n-1 edges.",
                "Edges = 9 − 1 = 8.",
                "Sum of degrees = 2 × |E| = 2 × 8 = 16 (Handshaking Lemma).",
            ],
            "answer": "8 edges; sum of degrees = 16.",
        },
        {
            "title": "Degree Sequence",
            "problem": "Can a simple graph have degree sequence (3,3,3,3,2)?",
            "steps": [
                "Check Handshaking Lemma: sum must be even.",
                "3+3+3+3+2 = 14. 14 is even ✓",
                "Check Erdős–Gallai or try to construct:",
                "5 vertices, 7 edges. Let vertices be v₁,v₂,v₃,v₄ (deg 3) and v₅ (deg 2).",
                "v₁-v₂, v₁-v₃, v₁-v₄, v₂-v₃, v₂-v₄ (5 edges, each v₁-v₄ has deg 2-3 so far)",
                "v₃-v₅, v₄-v₅ (add 2 edges: v₅ gets deg 2 ✓, v₃ and v₄ get deg 3 ✓)",
                "Result: valid simple graph exists.",
            ],
            "answer": "Yes, such a graph exists. (e.g., v₅ connects to v₃ and v₄; remaining edges among v₁-v₄)",
        },
    ],
}
