"""Study Mode — quiz questions (10 per topic)."""

QUIZZES: dict[str, list[dict]] = {
    "Set Theory": [
        {
            "q": "Which symbol means 'is an element of'?",
            "options": ["⊆", "∈", "∩", "∪"],
            "answer": 1,
            "explanation": "∈ means 'belongs to'. e.g., 3 ∈ {1,2,3}.",
        },
        {
            "q": "If A = {1,2,3} and B = {3,4,5}, what is A ∩ B?",
            "options": ["{1,2,3,4,5}", "{3}", "{1,2}", "{}"],
            "answer": 1,
            "explanation": "Intersection is the set of elements in BOTH A and B. Only 3 is in both.",
        },
        {
            "q": "If |A| = 4, how many subsets does A have?",
            "options": ["4", "8", "16", "24"],
            "answer": 2,
            "explanation": "The power set of a set with n elements has 2ⁿ subsets. 2⁴ = 16.",
        },
        {
            "q": "What is A − B?",
            "options": [
                "Elements in A or B",
                "Elements in A and B",
                "Elements in A but not in B",
                "Elements in B but not in A",
            ],
            "answer": 2,
            "explanation": "A − B (set difference) = {x | x ∈ A and x ∉ B}.",
        },
        {
            "q": "De Morgan's law states: (A ∪ B)' = ?",
            "options": ["A' ∪ B'", "A ∩ B", "A' ∩ B'", "A ∪ B'"],
            "answer": 2,
            "explanation": "De Morgan: complement of union = intersection of complements.",
        },
        {
            "q": "Which of these is the empty set?",
            "options": ["{0}", "{}", "{{}}","{ }"],
            "answer": 1,
            "explanation": "{} or ∅ is the empty set — it contains no elements.",
        },
        {
            "q": "If A = {a,b} and B = {1,2}, how many elements does A × B have?",
            "options": ["2", "4", "3", "8"],
            "answer": 1,
            "explanation": "|A × B| = |A| × |B| = 2 × 2 = 4. Pairs: (a,1),(a,2),(b,1),(b,2).",
        },
        {
            "q": "A = {1,2} and B = {2,1,1}. Are A and B equal?",
            "options": ["No, B has a repeated element", "Yes, sets are equal", "No, different order", "Depends on universe"],
            "answer": 1,
            "explanation": "Sets ignore duplicates and order. B simplifies to {1,2} = A.",
        },
        {
            "q": "Which identity is the absorption law?",
            "options": ["A ∪ (A ∩ B) = A", "A ∩ (A ∪ B) = A ∪ B", "A ∪ ∅ = A", "A ∩ U = A"],
            "answer": 0,
            "explanation": "Absorption: A ∪ (A ∩ B) = A and A ∩ (A ∪ B) = A.",
        },
        {
            "q": "What is the symmetric difference A ⊕ B?",
            "options": ["A ∩ B", "(A ∪ B) − (A ∩ B)", "A − B", "A ∪ B"],
            "answer": 1,
            "explanation": "Symmetric difference = elements in A or B but NOT both = (A∪B)−(A∩B).",
        },
    ],
    "Relations": [
        {
            "q": "Which property requires (a,a) ∈ R for all a in the set?",
            "options": ["Symmetric", "Transitive", "Reflexive", "Antisymmetric"],
            "answer": 2,
            "explanation": "Reflexive: every element must relate to itself.",
        },
        {
            "q": "If (1,2)∈R and (2,1)∈R, which property is satisfied?",
            "options": ["Reflexive", "Antisymmetric", "Transitive", "Symmetric"],
            "answer": 3,
            "explanation": "Symmetric: if (a,b)∈R then (b,a)∈R.",
        },
        {
            "q": "An equivalence relation must be:",
            "options": [
                "Reflexive, Symmetric, Transitive",
                "Reflexive, Antisymmetric, Transitive",
                "Symmetric and Transitive only",
                "Reflexive only",
            ],
            "answer": 0,
            "explanation": "Equivalence = Reflexive + Symmetric + Transitive.",
        },
        {
            "q": "A partial order must be:",
            "options": [
                "Reflexive, Symmetric, Transitive",
                "Reflexive, Antisymmetric, Transitive",
                "Irreflexive, Antisymmetric",
                "Symmetric and Transitive",
            ],
            "answer": 1,
            "explanation": "Partial order = Reflexive + Antisymmetric + Transitive (e.g., ≤).",
        },
        {
            "q": "R = {(1,1),(2,2),(3,3)} on {1,2,3}. What type of relation is this?",
            "options": ["Only symmetric", "Equivalence relation", "Partial order only", "Neither"],
            "answer": 1,
            "explanation": "It's reflexive (all (a,a)), symmetric (trivially), and transitive (trivially). Equivalence relation.",
        },
        {
            "q": "The transitive closure of R adds which pairs?",
            "options": [
                "All (a,a) pairs",
                "All (b,a) for each (a,b)",
                "All (a,c) where (a,b) and (b,c) exist",
                "No new pairs",
            ],
            "answer": 2,
            "explanation": "Transitive closure adds all pairs (a,c) reachable via chains in R.",
        },
        {
            "q": "If R is a relation from A to B, then R is a subset of:",
            "options": ["A ∪ B", "A ∩ B", "A × B", "𝒫(A)"],
            "answer": 2,
            "explanation": "A binary relation from A to B is any subset of the Cartesian product A × B.",
        },
        {
            "q": "Which algorithm computes transitive closure?",
            "options": ["Dijkstra's", "Warshall's", "Euler's", "Floyd's only"],
            "answer": 1,
            "explanation": "Warshall's algorithm computes transitive closure in O(n³).",
        },
        {
            "q": "R on {1,2,3}: {(1,2),(2,3),(1,3)}. Is R transitive?",
            "options": ["Yes", "No — missing (1,3)", "No — missing (3,1)", "No — missing (2,1)"],
            "answer": 0,
            "explanation": "(1,2)+(2,3)→(1,3) ✓ is the only case. (1,3) is already present.",
        },
        {
            "q": "Equivalence classes partition the set into:",
            "options": [
                "Overlapping subsets",
                "Disjoint subsets whose union is the full set",
                "Subsets ordered by size",
                "Pairs only",
            ],
            "answer": 1,
            "explanation": "Equivalence classes are always disjoint and their union is the entire set — a partition.",
        },
    ],
    "Propositional Logic": [
        {
            "q": "p → q is FALSE only when:",
            "options": ["p=T, q=T", "p=F, q=T", "p=T, q=F", "p=F, q=F"],
            "answer": 2,
            "explanation": "Implication is false only when the hypothesis (p) is true and conclusion (q) is false.",
        },
        {
            "q": "p → q is logically equivalent to:",
            "options": ["q → p", "¬p → ¬q", "¬p ∨ q", "p ∧ ¬q"],
            "answer": 2,
            "explanation": "p → q ≡ ¬p ∨ q is the fundamental equivalence for implication.",
        },
        {
            "q": "A tautology is a proposition that is:",
            "options": ["Always false", "Sometimes true", "Always true", "Undecidable"],
            "answer": 2,
            "explanation": "A tautology is true for every possible truth assignment of its variables.",
        },
        {
            "q": "¬(p ∧ q) ≡ ?  (De Morgan)",
            "options": ["¬p ∧ ¬q", "¬p ∨ ¬q", "p ∨ q", "¬p → q"],
            "answer": 1,
            "explanation": "De Morgan: NOT (p AND q) = (NOT p) OR (NOT q).",
        },
        {
            "q": "p ↔ q is true when:",
            "options": ["p=T only", "q=T only", "p and q have the same truth value", "p=T and q=F"],
            "answer": 2,
            "explanation": "Biconditional (if and only if) is true when both sides are equal.",
        },
        {
            "q": "How many rows does a truth table with 3 variables have?",
            "options": ["3", "6", "8", "9"],
            "answer": 2,
            "explanation": "With n variables, there are 2ⁿ rows. 2³ = 8.",
        },
        {
            "q": "Which is a contradiction?",
            "options": ["p ∨ ¬p", "p ∧ ¬p", "p → p", "p ∨ q"],
            "answer": 1,
            "explanation": "p ∧ ¬p is always false — a contradiction (a proposition can't be both T and F).",
        },
        {
            "q": "The contrapositive of p → q is:",
            "options": ["q → p", "¬p → ¬q", "¬q → ¬p", "p → ¬q"],
            "answer": 2,
            "explanation": "Contrapositive flips and negates both sides: ¬q → ¬p. It's equivalent to original.",
        },
        {
            "q": "p ∧ (p → q) simplifies to (by Modus Ponens logic):",
            "options": ["p ∨ q", "p → q", "q", "¬p"],
            "answer": 2,
            "explanation": "If p is true and p implies q, then q must be true (Modus Ponens).",
        },
        {
            "q": "Which connective has the highest precedence (binds tightest)?",
            "options": ["∧ (AND)", "∨ (OR)", "→ (IF-THEN)", "¬ (NOT)"],
            "answer": 3,
            "explanation": "Precedence order (highest to lowest): ¬, ∧, ∨, →, ↔.",
        },
    ],
    "Rules of Inference": [
        {
            "q": "Modus Ponens allows us to conclude q from:",
            "options": ["p ∨ q and ¬p", "p and p → q", "p → q and ¬p", "¬q and p → q"],
            "answer": 1,
            "explanation": "Modus Ponens: from p (true) and p→q, conclude q.",
        },
        {
            "q": "Modus Tollens allows us to conclude ¬p from:",
            "options": ["p → q and q", "p → q and ¬q", "¬p → q and ¬q", "p ∨ q and ¬q"],
            "answer": 1,
            "explanation": "Modus Tollens: from ¬q and p→q, conclude ¬p.",
        },
        {
            "q": "Hypothetical Syllogism chains which type of statements?",
            "options": ["Disjunctions", "Conjunctions", "Implications", "Negations"],
            "answer": 2,
            "explanation": "Hypothetical Syllogism: p→q and q→r gives p→r (chain of implications).",
        },
        {
            "q": "From 'p ∨ q' and '¬p', which rule gives us 'q'?",
            "options": ["Addition", "Simplification", "Disjunctive Syllogism", "Resolution"],
            "answer": 2,
            "explanation": "Disjunctive Syllogism eliminates one disjunct using its negation.",
        },
        {
            "q": "Addition rule says: from p, we can conclude:",
            "options": ["p ∧ q", "p ∨ q", "¬p", "p → q"],
            "answer": 1,
            "explanation": "Addition: p ⊢ p ∨ q. We can always weaken to a disjunction.",
        },
        {
            "q": "An argument is VALID when:",
            "options": [
                "All premises are true",
                "The conclusion is true",
                "Whenever all premises are true, the conclusion must also be true",
                "The premises are logically independent",
            ],
            "answer": 2,
            "explanation": "Validity = truth of premises FORCES truth of conclusion.",
        },
        {
            "q": "Resolution rule: from p∨q and ¬p∨r, we conclude:",
            "options": ["p ∧ r", "q ∧ ¬p", "q ∨ r", "¬q ∨ r"],
            "answer": 2,
            "explanation": "Resolution: (p∨q) ∧ (¬p∨r) ⊢ q∨r. Key in automated theorem proving.",
        },
        {
            "q": "Which rule lets us conclude p from p ∧ q?",
            "options": ["Addition", "Conjunction", "Simplification", "Modus Ponens"],
            "answer": 2,
            "explanation": "Simplification: p ∧ q ⊢ p. Extract one conjunct from a conjunction.",
        },
        {
            "q": "A fallacy is:",
            "options": [
                "A valid argument form",
                "An invalid argument form that looks valid",
                "A tautology",
                "A contradiction",
            ],
            "answer": 1,
            "explanation": "Common fallacies: Affirming the Consequent (p→q, q ⊢ p — INVALID), Denying the Antecedent.",
        },
        {
            "q": "Conjunction rule: from p and q separately, we can conclude:",
            "options": ["p ∨ q", "p ∧ q", "p → q", "¬p"],
            "answer": 1,
            "explanation": "Conjunction: having p and q as separate facts, we can write p ∧ q.",
        },
    ],
    "Proof Methods": [
        {
            "q": "In a direct proof of p → q, we start by:",
            "options": ["Assuming ¬q", "Assuming p and ¬q", "Assuming p", "Assuming q"],
            "answer": 2,
            "explanation": "Direct proof: assume the hypothesis p, then derive the conclusion q.",
        },
        {
            "q": "Proof by contradiction starts by assuming:",
            "options": ["The hypothesis is true", "The conclusion is false (¬q) along with p", "Both p and q are false", "Nothing"],
            "answer": 1,
            "explanation": "Contradiction: assume p ∧ ¬q, then find a logical impossibility.",
        },
        {
            "q": "The contrapositive of 'if n² is even, then n is even' is:",
            "options": [
                "If n is even, then n² is even",
                "If n² is odd, then n is odd",
                "If n is odd, then n² is odd",
                "If n is even, then n² is odd",
            ],
            "answer": 2,
            "explanation": "Contrapositive flips and negates: 'if n is odd, then n² is odd'.",
        },
        {
            "q": "Which proof method is used when you show the assumption leads to 0=1 or similar?",
            "options": ["Direct", "Contrapositive", "Cases", "Contradiction"],
            "answer": 3,
            "explanation": "Proof by contradiction ends when you derive an impossibility (0=1, n is both even and odd, etc.).",
        },
        {
            "q": "Proof by cases requires that the cases be:",
            "options": ["Mutually exclusive only", "Exhaustive only", "Both mutually exclusive and exhaustive", "Independent"],
            "answer": 2,
            "explanation": "Cases must cover all possibilities (exhaustive) and not overlap (mutually exclusive for clean proofs).",
        },
        {
            "q": "To prove '√2 is irrational', which method is most natural?",
            "options": ["Direct proof", "Proof by cases", "Proof by contradiction", "Proof by contrapositive"],
            "answer": 2,
            "explanation": "The classic proof assumes √2 = a/b (rational) and derives a contradiction with gcd(a,b)=1.",
        },
        {
            "q": "p → q and ¬q → ¬p are:",
            "options": ["Converses", "Inverses", "Contrapositives (logically equivalent)", "Contradictions"],
            "answer": 2,
            "explanation": "p→q and ¬q→¬p are contrapositives — always logically equivalent.",
        },
        {
            "q": "In a proof that 'there exists an even prime', you would:",
            "options": [
                "Prove all primes are even",
                "Exhibit the number 2 as a witness",
                "Assume no even prime exists",
                "Use induction",
            ],
            "answer": 1,
            "explanation": "Constructive existence proof: just provide the example. 2 is even and prime.",
        },
        {
            "q": "When proving 'for all integers n, n²+n is even', proof by cases uses:",
            "options": [
                "Cases n<0 and n≥0",
                "Cases n even and n odd",
                "Cases n=0 and n≠0",
                "No cases needed",
            ],
            "answer": 1,
            "explanation": "Every integer is either even or odd — two exhaustive cases.",
        },
        {
            "q": "A biconditional proof (p ↔ q) requires proving:",
            "options": ["Only p → q", "Only q → p", "Both p → q and q → p", "p ∧ q"],
            "answer": 2,
            "explanation": "p ↔ q means p → q AND q → p. Both directions must be proven.",
        },
    ],
    "Mathematical Induction": [
        {
            "q": "What are the two parts of a proof by mathematical induction?",
            "options": [
                "Hypothesis and Conclusion",
                "Base Case and Inductive Step",
                "Existence and Uniqueness",
                "Direct and Indirect",
            ],
            "answer": 1,
            "explanation": "Induction = Base Case (verify P(n₀)) + Inductive Step (P(k) → P(k+1)).",
        },
        {
            "q": "In the inductive step, what do we ASSUME?",
            "options": ["P(n+1) is true", "P(k) is true for arbitrary k ≥ n₀ (Inductive Hypothesis)", "P(1) is true", "P(n) is false"],
            "answer": 1,
            "explanation": "The inductive hypothesis assumes P(k) holds for some arbitrary k, then we prove P(k+1).",
        },
        {
            "q": "Prove Σᵢ₌₁ⁿ i = n(n+1)/2. Base case n=1: LHS = ?",
            "options": ["2", "0", "1", "1/2"],
            "answer": 2,
            "explanation": "For n=1: LHS = 1. RHS = 1·2/2 = 1. Base case checks out.",
        },
        {
            "q": "In strong induction, the inductive hypothesis assumes:",
            "options": [
                "P(k) for exactly one k",
                "P(j) for ALL j ≤ k",
                "P(k+1) is true",
                "P(1) through P(k-1)",
            ],
            "answer": 1,
            "explanation": "Strong induction assumes P(j) holds for all j from n₀ to k, giving a stronger hypothesis.",
        },
        {
            "q": "Induction proves statements for:",
            "options": [
                "Real numbers only",
                "Natural numbers (or integers from some starting point)",
                "Any set",
                "Finite sets only",
            ],
            "answer": 1,
            "explanation": "Mathematical induction applies to natural numbers (n=1,2,3,...) or integers starting from some n₀.",
        },
        {
            "q": "After the inductive step is complete, we conclude P(n) holds for:",
            "options": ["Only n=1 and n=k+1", "All n ≥ n₀", "n ≤ k only", "Infinitely many but not all n"],
            "answer": 1,
            "explanation": "By the principle of induction, P(n) holds for ALL n ≥ n₀.",
        },
        {
            "q": "For the formula Σᵢ₌₁ⁿ i² = n(n+1)(2n+1)/6, the inductive step adds which term?",
            "options": ["k", "k²", "(k+1)²", "k(k+1)"],
            "answer": 2,
            "explanation": "Moving from n=k to n=k+1 means adding the (k+1)-th term: (k+1)².",
        },
        {
            "q": "Why is the base case necessary?",
            "options": [
                "It isn't necessary",
                "Without it, the inductive step alone doesn't anchor the chain",
                "It proves the general case",
                "It replaces the inductive step",
            ],
            "answer": 1,
            "explanation": "Without the base case, induction is like dominoes with no first tile — the chain never starts.",
        },
        {
            "q": "To prove 2ⁿ > n for all n≥1, what is the base case?",
            "options": ["2⁰>0", "2¹>1", "2²>2", "2¹=1"],
            "answer": 1,
            "explanation": "n=1: 2¹=2 > 1 ✓. This anchors the induction.",
        },
        {
            "q": "Structural induction is used for proofs about:",
            "options": ["Real numbers", "Recursively defined structures (trees, strings, etc.)", "Infinite sets only", "Continuous functions"],
            "answer": 1,
            "explanation": "Structural induction follows the recursive definition of the structure (e.g., binary trees).",
        },
    ],
    "Sequences & Summations": [
        {
            "q": "In an arithmetic sequence with a₁=3 and d=4, what is a₅?",
            "options": ["15", "19", "12", "16"],
            "answer": 1,
            "explanation": "aₙ = a₁ + (n-1)d = 3 + 4·4 = 3 + 16 = 19.",
        },
        {
            "q": "What is Σᵢ₌₁⁵ i?",
            "options": ["10", "15", "20", "25"],
            "answer": 1,
            "explanation": "1+2+3+4+5=15. Formula: n(n+1)/2 = 5·6/2 = 15.",
        },
        {
            "q": "A geometric sequence has a₁=2 and r=3. What is a₄?",
            "options": ["18", "54", "27", "162"],
            "answer": 1,
            "explanation": "aₙ = a₁·r^(n-1) = 2·3³ = 2·27 = 54.",
        },
        {
            "q": "Σᵢ₌₁ⁿ i² equals:",
            "options": ["n(n+1)/2", "n(n+1)(2n+1)/6", "[n(n+1)/2]²", "n²"],
            "answer": 1,
            "explanation": "Sum of squares: Σi² = n(n+1)(2n+1)/6.",
        },
        {
            "q": "The Fibonacci sequence starts 1,1,2,3,5,8,... What comes next?",
            "options": ["10", "11", "12", "13"],
            "answer": 3,
            "explanation": "Each term = sum of previous two: 5+8=13.",
        },
        {
            "q": "An arithmetic sequence has a₁=10 and a₁₀=55. What is d?",
            "options": ["4", "5", "6", "45"],
            "answer": 1,
            "explanation": "aₙ = a₁+(n-1)d → 55=10+9d → 9d=45 → d=5.",
        },
        {
            "q": "Infinite geometric series converges when:",
            "options": ["|r| > 1", "|r| = 1", "|r| < 1", "r > 0"],
            "answer": 2,
            "explanation": "Sum = a/(1-r) is valid only when |r| < 1 (series converges).",
        },
        {
            "q": "Σᵢ₌₀³ 2ⁱ = ?",
            "options": ["6", "12", "15", "16"],
            "answer": 2,
            "explanation": "1+2+4+8=15. Formula: (r^(n+1)-1)/(r-1) = (2⁴-1)/1 = 15.",
        },
        {
            "q": "The closed form of Σᵢ₌₁ⁿ 1 (n times) is:",
            "options": ["n(n+1)/2", "n", "1", "2n"],
            "answer": 1,
            "explanation": "Adding 1 exactly n times equals n.",
        },
        {
            "q": "Sum of first n odd numbers (1+3+5+...+(2n-1)) equals:",
            "options": ["n(n+1)/2", "n²", "n(n-1)", "2n"],
            "answer": 1,
            "explanation": "1+3+5+...+(2n-1) = n². Try n=3: 1+3+5=9=3².",
        },
    ],
    "Combinatorics": [
        {
            "q": "How many ways can you arrange 5 books on a shelf?",
            "options": ["25", "120", "60", "32"],
            "answer": 1,
            "explanation": "5! = 5×4×3×2×1 = 120 permutations.",
        },
        {
            "q": "C(6,2) = ?",
            "options": ["12", "30", "15", "36"],
            "answer": 2,
            "explanation": "C(6,2) = 6!/(2!4!) = 30/2 = 15.",
        },
        {
            "q": "You choose a president and treasurer from 8 people. How many ways?",
            "options": ["16", "28", "56", "64"],
            "answer": 2,
            "explanation": "P(8,2) = 8×7 = 56. Order matters (president ≠ treasurer).",
        },
        {
            "q": "Pigeonhole principle: 367 people must include at least 2 with the same:",
            "options": ["Name", "Birthday", "Shoe size", "Phone number"],
            "answer": 1,
            "explanation": "There are 366 possible birthdays (leap year). 367 people → some box has ≥2.",
        },
        {
            "q": "Product rule: 3 shirts and 4 pants → number of outfits?",
            "options": ["7", "10", "12", "24"],
            "answer": 2,
            "explanation": "Product rule: 3 × 4 = 12 outfits.",
        },
        {
            "q": "How many binary strings of length 4 are there?",
            "options": ["4", "8", "16", "12"],
            "answer": 2,
            "explanation": "Each position has 2 choices: 2⁴ = 16.",
        },
        {
            "q": "C(n,r) = C(n, n-r). If C(10,3) = 120, what is C(10,7)?",
            "options": ["70", "210", "120", "720"],
            "answer": 2,
            "explanation": "C(10,7) = C(10,10-7) = C(10,3) = 120.",
        },
        {
            "q": "|A ∪ B| where |A|=20, |B|=15, |A∩B|=5 is:",
            "options": ["30", "35", "40", "25"],
            "answer": 0,
            "explanation": "|A∪B| = 20+15-5 = 30.",
        },
        {
            "q": "P(n,r) = r! × C(n,r). This means permutations relate to combinations by:",
            "options": [
                "Dividing by r!",
                "Multiplying by r! (arranging chosen elements)",
                "Adding r!",
                "Taking the square root",
            ],
            "answer": 1,
            "explanation": "After choosing r items (C(n,r) ways), we can arrange them in r! ways: P(n,r) = r!·C(n,r).",
        },
        {
            "q": "How many 3-digit PINs are possible (digits 0-9, repetition allowed)?",
            "options": ["720", "1000", "900", "504"],
            "answer": 1,
            "explanation": "10 choices for each of 3 digits: 10³ = 1000.",
        },
    ],
    "Graph Theory": [
        {
            "q": "The sum of all vertex degrees in a graph equals:",
            "options": ["|V|", "|E|", "2|E|", "|V|+|E|"],
            "answer": 2,
            "explanation": "Handshaking Lemma: Σdeg(v) = 2|E| (each edge contributes 2 to total degree).",
        },
        {
            "q": "An Euler circuit exists iff:",
            "options": [
                "The graph is connected and all vertices have even degree",
                "All vertices have degree ≥ 2",
                "Exactly 2 vertices have odd degree",
                "The graph is bipartite",
            ],
            "answer": 0,
            "explanation": "Euler circuit: connected + every vertex has even degree.",
        },
        {
            "q": "K₄ (complete graph on 4 vertices) has how many edges?",
            "options": ["4", "6", "8", "12"],
            "answer": 1,
            "explanation": "Kₙ has n(n-1)/2 edges. K₄: 4×3/2 = 6.",
        },
        {
            "q": "A tree with n vertices has how many edges?",
            "options": ["n", "n-1", "n+1", "n(n-1)/2"],
            "answer": 1,
            "explanation": "A tree is a connected acyclic graph: it always has exactly n-1 edges.",
        },
        {
            "q": "A bipartite graph contains:",
            "options": [
                "Only odd cycles",
                "No odd-length cycles",
                "No cycles at all",
                "Exactly one cycle",
            ],
            "answer": 1,
            "explanation": "A graph is bipartite if and only if it contains no odd-length cycles.",
        },
        {
            "q": "Two graphs are isomorphic if they have:",
            "options": [
                "Same vertex labels",
                "Same number of vertices only",
                "A structure-preserving bijection between their vertex sets",
                "Same degree for all vertices",
            ],
            "answer": 2,
            "explanation": "Isomorphism = bijection f:V₁→V₂ where (u,v)∈E₁ iff (f(u),f(v))∈E₂.",
        },
        {
            "q": "Which vertex degree is called 'isolated'?",
            "options": ["Degree 0", "Degree 1", "Degree 2", "Maximum degree"],
            "answer": 0,
            "explanation": "An isolated vertex has degree 0 — no edges connect to it.",
        },
        {
            "q": "An Euler PATH (not circuit) exists when:",
            "options": [
                "All vertices have even degree",
                "Exactly 2 vertices have odd degree",
                "Exactly 1 vertex has odd degree",
                "No vertex has odd degree",
            ],
            "answer": 1,
            "explanation": "Euler path: exactly 2 odd-degree vertices (they are the start and end).",
        },
        {
            "q": "A connected graph with no cycles is called:",
            "options": ["Complete graph", "Bipartite graph", "Tree", "Planar graph"],
            "answer": 2,
            "explanation": "A tree is a connected acyclic graph.",
        },
        {
            "q": "The degree sequence of K₃ is:",
            "options": ["(1,1,1)", "(2,2,2)", "(3,3,3)", "(0,1,2)"],
            "answer": 1,
            "explanation": "K₃ is a triangle: each vertex connects to both others → degree 2 each.",
        },
    ],
}
